# Generated by Django 3.2 on 2021-05-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210524_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_profile',
        ),
    ]
